export interface Scoreboard {
  id: number;
  use_sport_preset: boolean;
  language_code: string;
  is_qtr: boolean;
  is_time: boolean;
  is_playclock: boolean;
  is_downdistance: boolean;
  is_tournament_logo: boolean;
  is_main_sponsor: boolean;
  is_team_a_start_offense?: boolean | null;
  is_team_b_start_offense?: boolean | null;
  is_team_a_start_defense?: boolean | null;
  is_team_b_start_defense?: boolean | null;
  is_home_match_team_lower?: boolean | null;
  is_away_match_team_lower?: boolean | null;
  is_football_qb_full_stats_lower?: boolean | null;
  is_match_player_lower?: boolean | null;
  is_sponsor_line: boolean;
  is_match_sponsor_line?: boolean | null;
  team_a_game_color: string;
  use_team_a_game_color?: boolean | null;
  team_b_game_color: string;
  use_team_b_game_color?: boolean | null;
  team_a_game_title?: string | null;
  use_team_a_game_title?: boolean | null;
  team_b_game_title?: string | null;
  use_team_b_game_title?: boolean | null;
  team_a_game_logo?: string | null;
  use_team_a_game_logo?: boolean | null;
  team_b_game_logo?: string | null;
  use_team_b_game_logo?: boolean | null;
  scale_tournament_logo?: number | null;
  scale_main_sponsor?: number | null;
  scale_logo_a?: number | null;
  scale_logo_b?: number | null;
  is_flag?: boolean | null;
  is_goal_team_a?: boolean | null;
  is_goal_team_b?: boolean | null;
  is_timeout_team_a?: boolean | null;
  is_timeout_team_b?: boolean | null;
  match_id?: number | null;
  player_match_lower_id?: number | null;
  football_qb_full_stats_match_lower_id?: number | null;
}

export interface ScoreboardCreate {
  use_sport_preset?: boolean;
  language_code?: string;
  is_qtr?: boolean;
  is_time?: boolean;
  is_playclock?: boolean;
  is_downdistance?: boolean;
  is_tournament_logo?: boolean;
  is_main_sponsor?: boolean;
  is_team_a_start_offense?: boolean | null;
  is_team_b_start_offense?: boolean | null;
  is_team_a_start_defense?: boolean | null;
  is_team_b_start_defense?: boolean | null;
  is_home_match_team_lower?: boolean | null;
  is_away_match_team_lower?: boolean | null;
  is_football_qb_full_stats_lower?: boolean | null;
  is_match_player_lower?: boolean | null;
  is_sponsor_line?: boolean;
  is_match_sponsor_line?: boolean | null;
  team_a_game_color?: string;
  use_team_a_game_color?: boolean | null;
  team_b_game_color?: string;
  use_team_b_game_color?: boolean | null;
  team_a_game_title?: string | null;
  use_team_a_game_title?: boolean | null;
  team_b_game_title?: string | null;
  use_team_b_game_title?: boolean | null;
  team_a_game_logo?: string | null;
  use_team_a_game_logo?: boolean | null;
  team_b_game_logo?: string | null;
  use_team_b_game_logo?: boolean | null;
  scale_tournament_logo?: number | null;
  scale_main_sponsor?: number | null;
  scale_logo_a?: number | null;
  scale_logo_b?: number | null;
  is_flag?: boolean | null;
  is_goal_team_a?: boolean | null;
  is_goal_team_b?: boolean | null;
  is_timeout_team_a?: boolean | null;
  is_timeout_team_b?: boolean | null;
  match_id?: number | null;
  player_match_lower_id?: number | null;
  football_qb_full_stats_match_lower_id?: number | null;
}

export interface ScoreboardUpdate {
  use_sport_preset?: boolean;
  language_code?: string;
  is_qtr?: boolean;
  is_time?: boolean;
  is_playclock?: boolean;
  is_downdistance?: boolean;
  is_tournament_logo?: boolean;
  is_main_sponsor?: boolean;
  is_team_a_start_offense?: boolean | null;
  is_team_b_start_offense?: boolean | null;
  is_team_a_start_defense?: boolean | null;
  is_team_b_start_defense?: boolean | null;
  is_home_match_team_lower?: boolean | null;
  is_away_match_team_lower?: boolean | null;
  is_football_qb_full_stats_lower?: boolean | null;
  is_match_player_lower?: boolean | null;
  is_sponsor_line?: boolean;
  is_match_sponsor_line?: boolean | null;
  team_a_game_color?: string;
  use_team_a_game_color?: boolean | null;
  team_b_game_color?: string;
  use_team_b_game_color?: boolean | null;
  team_a_game_title?: string | null;
  use_team_a_game_title?: boolean | null;
  team_b_game_title?: string | null;
  use_team_b_game_title?: boolean | null;
  team_a_game_logo?: string | null;
  use_team_a_game_logo?: boolean | null;
  team_b_game_logo?: string | null;
  use_team_b_game_logo?: boolean | null;
  scale_tournament_logo?: number | null;
  scale_main_sponsor?: number | null;
  scale_logo_a?: number | null;
  scale_logo_b?: number | null;
  is_flag?: boolean | null;
  is_goal_team_a?: boolean | null;
  is_goal_team_b?: boolean | null;
  is_timeout_team_a?: boolean | null;
  is_timeout_team_b?: boolean | null;
  player_match_lower_id?: number | null;
  football_qb_full_stats_match_lower_id?: number | null;
}
